import "./globals.css";
import { Roboto_Mono } from "next/font/google";

const inter = Roboto_Mono({ subsets: ["latin"] });
// force reload of data
export const dynamic = "force-dynamic";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className="">
      <body className={inter.className}>
        <div className="bg-pink-600">
          <div className="container min-h-screen py-4 mx-auto">{children}</div>
        </div>
      </body>
    </html>
  );
}
